# Generated by Django 5.2.1 on 2025-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
